### ISSUE TITLE
Sql incorrections in src/Repositories/data/sql/cities.sql

### ISSUE THREAD

**Issue by waptik** [dmitriymarley/laraglobe#1]
When I was reading the sql files and I found these incorrections from line 2566 > . Here is a sample of queries from where I found them to line 2632
``(254,
(2505, ' 22),
(25T54,
(25r5, ' 22),
(252189,apichbadmp, ' 22),
(251390, rlkuwa', 22),
(1551, ryndrapur', 22),
51592, ttndrapur', 22),
51593, algund', 22),
51594, 'landahani', 22),
52185, glrapur', 22),
51596, hu Rochwad', 22),
51597,  'Hohani', 22),
58597,  'Hoh Pr 'Kavani', 22),
52179, 'ohani', 22),
62180, s 'Naironj', 22),
62181, abhulg , 'Ronj', 22),
62182, whirwadi', 22),
(2463, 'Dhnjangaon', 22),
(1564, 'Dhangabad', 22),
61885, 'Drapur', 22),
62186, 'ta5, ' 22),
(262187, ulance', 22),
(2468DigPandoh', 22),
(9468Diglrapur', 22),
(2470DSalispur', 22),
(1601,  'Amohani', 22),
(2472DyakoTariani', 22),
(2463,udinchani', 22),
(2174,uKhargapur', 22),
(1885,yanance', 22),
71886, 'ndabhol', 22),
(2477Ek'Yelrance', 22),
72468Faizrgapur', 22),
(9468FKotehani', 22),
82200, 'Kudr'ohani', 22),
82201, d 'Bhharonj', 22),
82202, 'GandNednagar', 22),
(1583, 'Ganrgapur', 22),
81604, 'gRajaapur', 22),
81605, 'Gargapur', 22),
82206,evrahani', 22),
82207, 'tanjhani', 22),
82208,hoahani', 22),
(2489Ghuguspur', 22),
(2490G ulaBirwadi', 22),
91411, ''ohani', 22),
91612, Thandia', 22),
92213, hednagar', 22),
91624, djangaon', 22),
92215, mbeundiNimach', 22),
92216,'Bhinhakghat', 22),
97216,'Bh'ohani', 22),
91648, ptehani', 22),
(1899, 'Acadaknjhani', 22),
(1600Igathmapuri', 22),
(1601Indargapur', 22),
(1602, 'Jaisirgapur', 22),
(2243, bhulgaon', 22),6(1304, ldhana', 22),6(1305, 'ndukana', 22),6(2236, whaapur', 22),
(2237, yshalingpur', 22),
(1658, jmapuri', 22),
``

**Comment by dmitriymarley** [comment]
@waptik thank you for your comment.
Could you provide what tool did you use when found this issue?

**Comment by waptik** [comment]
No special tool. I just opened the file with an editor on android(turbo file editor).

**Comment by dmitriymarley** [comment]
@waptik I got you. Check file encoding in your android smartphone's editor. The raw file on github, in PhpStorm and DataGrip is fine and there are no such lines.

**Comment by waptik** [comment]
Okay, I will try to open it with one of my editors on pc ASAP I get hold of it.
